sudo: required
dist: trusty
language: python
python:
  - "3.4"
env:
  global:
    - DEBIAN_FRONTEND=noninteractive
addons:
  postgresql: "9.4"
services:
  - postgresql
  - redis-server
  - rabbitmq-server
  - memcached
before_install:
  - travis_retry sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - sudo echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - travis_retry sudo wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  - sudo echo "deb http://packages.elastic.co/elasticsearch/2.0/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elastic.list
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install -y elasticsearch mongodb-org

  - sudo service elasticsearch start
install:
  - sleep 10

  - redis-cli 'INFO' | grep redis_version
  - echo exit | mongo
  - rabbitmqctl status | grep -ai '"rabbitmq"'
  - memcached -h | grep memcached | grep 1
  - curl -XGET "localhost:9200"
  - psql -c "SELECT version();"

  - which pip
  - pip install virtualenv
  - virtualenv env3
  - source env3/bin/activate
  - travis_retry pip install -U pip
  - travis_retry pip install -U setuptools
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt
before_script:
  - psql -c "create database app;" -U postgres
script:
  - flake8 app
  - frosted -r app
  - isort --check-only -rc app --diff
  - cd app
  - python manage.py check
  - python manage.py test -v 2 --with-coverage
notifications:
  email: false
