sudo: false
language: python
python:
  - "3.4"
env:
  global:
    - DEBIAN_FRONTEND=noninteractive
before_install:
  - which pip
  - python --version
  - curl -XGET "localhost:9200"
  - redis-cli "INFO" | grep version
  - mongod --version
  - psql --version
services:
  - mongodb
  - elasticsearch
  - postgresql
  - rabbitmq-server
  - redis-server
  - memcached
addons:
  postgresql: "9.4"
install:
  - pip3.4 install virtualenv
  - virtualenv env3
  - source env3/bin/activate
  - pip install -U pip
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - sleep 10
  - psql -c "create database app;" -U postgres
script:
  - flake8 app
  - frosted -r app
  - isort --check-only -rc app --diff
  - cd app
  - python manage.py check
  - python manage.py test -v 2 --with-coverage
notifications:
  email: false
